#!/usr/bin/env python3
"""Build the Apps Script version of the Mural from the POS sources.

  web/view-mural.js + web/mural.css + gas/shim-*.js  →  web/gas/mural.html
  gas/mural2.gs                                      →  web/gas/mural2.gs.txt

Both outputs are published on GitHub Pages so the Apps Script editor can
pull them in. They contain code only — no board data.
"""
import os, re, sys

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
WEB = os.path.join(ROOT, 'web')
OUT = os.path.join(WEB, 'gas')
os.makedirs(OUT, exist_ok=True)

js = open(os.path.join(WEB, 'view-mural.js')).read()
css = open(os.path.join(WEB, 'mural.css')).read()
pre = open(os.path.join(ROOT, 'gas', 'shim-pre.js')).read()
post = open(os.path.join(ROOT, 'gas', 'shim-post.js')).read()

def must(old, new, count=None):
    global js
    n = js.count(old)
    if n == 0 or (count is not None and n != count):
        sys.exit(f'build: expected {count or ">=1"} of {old!r}, found {n}')
    js = js.replace(old, new)

must("document.getElementById('main')", "muralHost()")
must("muralProjects = state.data.mural_projects || [];",
     "muralProjects = (state.data.mural_projects || []).map(_m2Clean).map(function (p) { if (!p.title && p.name) p.title = p.name; return p; });")

# speed: board-scoped loading instead of reading every board
must("const allEls = state.data.mural_elements || await apiGet('mural_elements');", "const allEls = await _m2SummaryEls();")
must("""        const res = await apiGet('mural_elements');
        // Sync with global state for dashboard counts
        state.data.mural_elements = res || [];""", """        const res = await _m2BoardElements(muralActiveProjectId);""")
must("const fresh = await apiGet('mural_elements');", "const fresh = await _m2BoardElements(muralActiveProjectId, true);")
must("const all = await apiGet('mural_elements');", "const all = await _m2FamilyElements(ids);")
must("try { await manualMuralSync(); } catch (_) {} // don't lose edits on this board", "/* GAS: unsaved changes are sent by openMuralProject (no waiting) */")

if '</script' in js.lower():
    sys.exit('build: view-mural.js contains </script — would break the HTML file')

HOST_CSS = """
/* ---- host bridge for the Apps Script app ---- */
:root {
  --surface-1: #FFFFFF; --surface-2: #F1F5F9; --surface-3: #E2E8F0; --surface-base: #F8FAFC;
  --text-1: #0F172A; --text-2: #334155; --text-3: #64748B; --border-color: #E2E8F0;
  --primary: #23B79C; --primary-soft: rgba(35, 183, 156, 0.10);
  --danger: #DC2626; --danger-soft: rgba(220, 38, 38, 0.15);
}
.mural-page { z-index: 200 !important; }
body:has(.mural-page) aside, body:has(.mural-page) #main-header { display: none !important; }
body:has(.mural-page) .view-section, body:has(.mural-page) main { transform: none !important; filter: none !important; }
#view-mural .mural-dashboard { height: 100%; overflow-y: auto; box-sizing: border-box; }
#universalModal .modal-box:has(.mural-imp) { max-width: 640px; padding: 28px; }
#view-mural .btn, #universalModal .btn { display: inline-flex; align-items: center; justify-content: center; gap: 6px;
  padding: 10px 16px; border-radius: 12px; font-weight: 700; font-size: 14px; cursor: pointer; border: 1px solid transparent; }
#view-mural .btn.primary, #universalModal .btn.primary { background: #0F172A; color: #fff; }
#view-mural .btn.primary:hover, #universalModal .btn.primary:hover { background: #000; }
#view-mural .btn.secondary, #universalModal .btn.secondary { background: #F1F5F9; color: #334155; border-color: #E2E8F0; }
#view-mural .btn:disabled, #universalModal .btn:disabled { opacity: .5; cursor: default; }
#universalModal .nc-ed-title, #universalModal .nc-ed-cat-select { width: 100%; box-sizing: border-box; border: 1px solid #E2E8F0;
  border-radius: 12px; background: #F8FAFC; color: #0F172A; outline: none; }
#universalModal .nc-ed-title:focus, #universalModal .nc-ed-cat-select:focus { border-color: #23B79C; }
.m2-viewers { display: none; align-items: center; gap: 4px; margin-right: 6px; }
.m2-av { width: 28px; height: 28px; border-radius: 50%; background: #23B79C; color: #fff; font-size: 11px; font-weight: 800;
  display: inline-flex; align-items: center; justify-content: center; box-shadow: 0 0 0 2px #fff; margin-left: -6px; }
.m2-av:first-child { margin-left: 0; }
.m2-av-label { font-size: 12px; font-weight: 600; color: #64748B; margin-left: 6px; white-space: nowrap; }
@media (max-width: 640px) { .m2-av-label { display: none; } }
"""

html = ("<!-- Mural (POS port) — generated by gas/build.py. Rebuild instead of editing here. -->\n"
        "<style>\n" + css + "\n" + HOST_CSS + "\n</style>\n"
        "<script>\n" + pre + "\n" + js + "\n" + post + "\n</script>\n")
open(os.path.join(OUT, 'mural.html'), 'w').write(html)
open(os.path.join(OUT, 'mural2.gs.txt'), 'w').write(open(os.path.join(ROOT, 'gas', 'mural2.gs')).read())
print('built', os.path.join(OUT, 'mural.html'), len(html), 'bytes')
