// =====================================================================
// Mural (POS port) — host bridge for the Apps Script app
// Generated by gas/build.py from web/view-mural.js + web/mural.css.
// Do not edit this file in Apps Script — rebuild instead.
// =====================================================================
if (!window.state) window.state = { data: {} };
if (!window.state.data) window.state.data = {};

function muralHost() { return document.getElementById('view-mural') || document.getElementById('main'); }

function escapeHtml(str) {
    return (str === null || str === undefined) ? '' : String(str).replace(/[&<>"']/g, function (m) {
        return ({ '&': '&amp;', '<': '&lt;', '>': '&gt;', '"': '&quot;', "'": '&#39;' })[m];
    });
}
function toast(msg, type) { if (typeof window.showToast === 'function') window.showToast(msg, type || 'success'); else console.log(msg); }

// ---------- server calls ----------
function _m2run(fn) {
    var args = Array.prototype.slice.call(arguments, 1);
    return new Promise(function (res, rej) {
        var r = google.script.run.withSuccessHandler(res).withFailureHandler(rej);
        r[fn].apply(r, args);
    });
}

// Sheet values come back with '' for empty cells — drop them so the code sees "not set"
function _m2Clean(o) {
    var c = {};
    Object.keys(o || {}).forEach(function (k) {
        var v = o[k];
        if (v === '' || v === null || v === undefined) return;
        if (v === 'TRUE') v = true; else if (v === 'FALSE') v = false;
        c[k] = v;
    });
    return c;
}
var _M2_VOLATILE = { updated_at: 1, updated_by: 1, created_at: 1, created_by: 1, user_id: 1 };
function _m2Key(el) {
    var keys = Object.keys(el || {}).filter(function (k) { return !_M2_VOLATILE[k] && el[k] !== '' && el[k] !== null && el[k] !== undefined; }).sort();
    return JSON.stringify(keys.map(function (k) { var v = el[k]; return [k, typeof v === 'number' ? Math.round(v * 100) / 100 : String(v)]; }));
}

// Last known saved state of every item: id → {key, pid}
var _m2Base = {};
var _m2Ver = {};
function _m2SetBase(el) { _m2Base[String(el.id)] = { key: _m2Key(el), pid: String(el.project_id) }; }

function _m2Delta(pid, list) {
    var upserts = [], ids = {};
    (list || []).forEach(function (el) {
        if (!el || el.id === undefined) return;
        if (String(el.id).indexOf('temp_line_') === 0 && typeof muralDrawingLine !== 'undefined' && muralDrawingLine && muralDrawingLine.id === el.id) return;
        ids[String(el.id)] = true;
        var b = _m2Base[String(el.id)];
        if (!b || b.key !== _m2Key(el)) upserts.push(el);
    });
    var deletes = Object.keys(_m2Base).filter(function (id) { return _m2Base[id].pid === String(pid) && !ids[id]; });
    return { upserts: upserts, deletes: deletes };
}

async function apiGet(key) {
    var rows = await _m2run('mural2Get', key);
    rows = (rows || []).map(_m2Clean);
    // one object per id (older saves could duplicate rows)
    var seenIds = {}, uniq = [];
    for (var i = rows.length - 1; i >= 0; i--) { var k = String(rows[i].id); if (seenIds[k]) continue; seenIds[k] = true; uniq.unshift(rows[i]); }
    rows = uniq;
    if (key === 'mural_elements') rows.forEach(_m2SetBase);
    return rows;
}

async function _m2SendDelta(pid, d) {
    var before = _m2Ver[pid] || 0;
    var res = await _m2run('mural2Post', { action: 'syncMuralDelta', payload: { project_id: pid, upserts: d.upserts, deletes: d.deletes } });
    if (res && res.success) {
        d.upserts.forEach(function (el) { el.project_id = el.project_id || pid; _m2SetBase(el); });
        d.deletes.forEach(function (id) { delete _m2Base[id]; });
        if (res.version !== undefined) {
            // someone else also saved in between → pull their changes
            if (before && res.version > before + 1) setTimeout(function () { _m2Pull(pid); }, 50);
            _m2Ver[pid] = res.version;
        }
    }
    return res;
}

async function apiPost(req, extra) {
    // Mural keyboard-shortcut settings → kept per person in this browser
    if (typeof req === 'string') {
        try { localStorage.setItem('m2.settings', JSON.stringify(extra && extra.payload ? extra.payload : extra)); } catch (_) {}
        return { success: true, id: 'local' };
    }
    if (req && req.action === 'syncMuralElements' && req.payload && String(req.payload.project_id) === String(muralActiveProjectId)) {
        var pid = String(req.payload.project_id);
        var d = _m2Delta(pid, req.payload.elements);
        if (!d.upserts.length && !d.deletes.length) return { success: true };
        return _m2SendDelta(pid, d);
    }
    var res = await _m2run('mural2Post', req);
    if (req && req.action === 'syncMuralElements' && res && res.success) {
        (req.payload.elements || []).forEach(function (el) { el.project_id = req.payload.project_id; _m2SetBase(el); });
    }
    if (res && res.data) res.data = _m2Clean(res.data);
    return res;
}
